#!/usr/bin/env bash
# vim:ts=4:sw=4:noet:ft=bash
#
# Script to package LetsDNS for distribution and to handle PyPI uploads.
# You need Python modules 'wheel' and 'twine' to publish to PyPI, and
# Ruby Gems 'asciidoctor' and 'asciidoctor-diagram' to generate HTML
# documentation.

set -euo pipefail

function usage() {
	local n="$(basename $0)"
	cat >&2 <<EOT
Usage: ${n} {clean | dist | docs}
       ${n} push
       ${n} upload [repository]
       ${n} setver {version}
EOT
	exit 1
}

function do_clean() {
	/bin/rm -r build/* dist/*
}

function do_dist() {
	python setup.py sdist bdist_wheel
}

function do_docs() {
	local ad="${HOME}/.gem/ruby/3.0.0/bin/asciidoctor"
	local opt=(
		'-r' 'asciidoctor-diagram'
		'-v'
		'LetsDNS.adoc'
	)
	pushd docs >/dev/null
	"${ad}-pdf" -a toc=preamble "${opt[@]}"
	${ad} -a toc=right -o index.html "${opt[@]}"
	popd >/dev/null
}

function do_push() {
	local r
	for r in $(git remote); do
		git push ${r}
	done
}

function do_upload() {
	if [ $# -gt 0 ]; then
		repo="$1"
	fi
	local opt=(
		'-sign'
		'-i'
		'6AE2A84723D56D985B340BC08E5FA4709F69E911'
		'-r'
		"${repo:-testpypi}"
	)
	twine upload "${opt[@]}" dist/*
}

function do_setver() {
	[ $# -gt 0 ] || usage
	sed -E -i -e "s/^(VERSION = ).+/\1'${1}'/" letsdns/__init__.py
	sed -E -i -e "s/^(:revnumber:).+/\1 ${1}/" docs/letsdns.adoc
	sed -E -i -e "s/^(:revdate:).+/\1 $(date +%F)/" docs/letsdns.adoc
}

[ $# -gt 0 ] || usage
arg="$1"
shift
case "$arg" in
	clean|docs|push)
		do_$arg
		;;
	dist|upload)
		source .venv/bin/activate
		do_$arg "$@"
		;;
	setver)
		do_$arg "$@"
		;;
	*)
		usage
		;;
esac
