# vim:ts=2:sw=2:et

stages:
- build
- test

pages:
  image: sphinxdoc/sphinx
  stage: build
  when: manual
  script:
    - make -C docs cibuild
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public

python-tests:
  image: python:3.7
  stage: test
  when: manual
  before_script:
    - pip install -r requirements.txt
  script:
    - make -C tests --warn-undefined-variables
