# vim:ts=2:sw=2:et

image: sphinxdoc/sphinx

stages:
- test
- sphinx

pages:
  stage: sphinx
  when: manual
  script:
    - make -C docs cibuild
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public

sast:
  stage: test
  when: manual
include:
- template: Security/SAST.gitlab-ci.yml
