# vim:ft=yaml:ts=2:sw=2:et

name: LetsDNS project workflow
on: push
env:
  CONF: citest.conf

jobs:
  build-documentation:
    name: Documentation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Generate documentation
        run: make -C docs cibuild SED_INPLACE="sed -i''"

      - name: Store documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LetsDNS-documentation
          path: docs/build/html/*

  build-python:
    name: Python build and tests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python code style
        run: pycodestyle --config=.pycodestyle letsdns/*.py

      - name: Run tests with coverage
        run: make -C tests coverage UNITTEST_CONF=$CONF

      - name: Build Python artifacts
        run: make dist

      - name: Store Python artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LetsDNS-software
          path: dist/*
