# vim:ft=yaml:ts=2:sw=2:et

name: LetsDNS project workflow
on: push
env:
  CONF: citest.conf

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Generate documentation
        run: make -C docs cibuild

      - name: Store documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LetsDNS-documentation
          path: docs/build/html/*

  build-python:
    name: Build and test Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: make -C tests coverage UNITTEST_CONF=$CONF

      - name: Build Python artifacts
        run: make dist

      - name: Store Python artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LetsDNS-software
          path: dist/*
